version: "3"

services:
  app:
    image: hexletcomponents/devops-example-app:test

  caddy:
    build:
      context: .
      dockerfile: services/caddy/Dockerfile
    image: hexletcomponents/devops-example-caddy
